### ISSUE TITLE
Feature request: Load/Save sparsehash

### ISSUE THREAD

**Issue by GerbertKaandorp** [erhanbaris/SymSpellPlusPlus#2]
Hi erhanbaris

Thanks for fixing the previous bugs. Everything works great now for my test cases!

I have a request:
I've seen on https://github.com/sparsehash/sparsehash that I/O is supported on the hashmap.
Do you think it's possible to add read/write to disk for map<size_t, dictionaryItemContainer> dictionary; ?
This would be of enormous value because i'm trying to work with large amounts of data and the starttime with edit distance 3 is becoming quite a bottleneck :) 
(ps my longest string is 54 characters generating over 100.000 deletes ! )

Thanks again for your help!

Gerbert

**Comment by erhanbaris** [comment]
Hi Gerbert
IO operations available at sparse_hash_map but It has performance problem and It could make our code more slower to finding results.
Also Google Guys told "dense_hash_map also has the API,
but it has not yet been implemented, and writes will always fail". 
One guy implemented read/write operation over dense_hash_map but I did not test his code.
https://github.com/greg7mdp/sparsepp
Let me check the solutions and than I will give you a feedback
Thanks

**Comment by erhanbaris** [comment]
Hi Gerbert
I implemented 2 function for loading and saving dataset to disk. 
msgpack-c need added to your project for this operations.
https://github.com/msgpack/msgpack-c

If you get any problem please let me know.

**Comment by GerbertKaandorp** [comment]
Hi erhanbaris

Thanks again for your implementation. This is fantastic!
I just did a first test and it seems to work!

Here is some of my debug output:
Loading data from ../final_unique.csv.
352.036 strings loaded.
Edit Distance = 2
Dictionary size:29.919.754
It took me 319.398 seconds.

Then I saved the data with the new function
Resulting in a 526.3MB file

I then load the data:
It took me 148.846 seconds.

As you can see it's more then twice as fast!
Awesome.

I'm going to try it later (tomorrow, it's 20:15 here now :) )
with Edit Distance 3... Should be fun!

Cheers,
Gerbert

ps. If there is anything I can help you with let me know.

**Comment by erhanbaris** [comment]
Hi Gerbert
Please share with me distance 3 results :)
Thanks

**Comment by GerbertKaandorp** [comment]
Hi erhanbaris,

No luck yet :(

At first it did not work at all.
Creating the dictionary took forever.
Especially on when the strings got very long.
I started checking why it took so long and basically all the time was spend in "Edits"
I though maybe its the recursion.
So I implemented the Edits function without recursion
```
    CUSTOM_SET<string> Edits(string word, size_t editDistance, CUSTOM_SET<string> & deletes)
    {

        set<string> queue;
        queue.insert(word);
        for (size_t d = 0; d < editDistanceMax; ++d)
        {
            set<string> temp_queue;
            for(auto word : queue) {
                if (word.size() > 1){
                    for (size_t i = 0; i < word.size(); ++i)
                    {
                        string wordClone = word;
                        string del = wordClone.erase(i, 1);
                        if (!deletes.count(del))
                        {
                            deletes.insert(del);
                        }
                        if (!temp_queue.count(del))
                        {
                            temp_queue.insert(del);
                        }
                    }
                }
            }
            queue = temp_queue;
        }
        return deletes;
    }
```

Again, its a long time ago I did a lot of C so I hope my implementation is good :)
But as far as I can tell, it works
Generating 3762 deletes from a 32 length string originally took:
0.642264 seconds.
with the new implementation it takes:
0.0322957 seconds.
20 times faster :)

Then I tried my large testcase again:
352.036 strings loaded.
Edit Distance = 3
It took me 1574.27 seconds.

It worked! Although it took 26 minutes to generate.
It also saved a file of 1.6 GB

Now I tried loading it again, but unfortunately I got:
Exception: std::bad_cast

I dont know why.

I also added these 2 functions:
```
    void Setup(size_t editDistanceMax_, size_t verbose_)
    {
        editDistanceMax = editDistanceMax_;
        verbose = verbose_;
    }

    string Stats()
    {
        return std::to_string(dictionary.size());

    }
```

They help my with integration a bit.

Thanks for listening
Cheers,
Gerbert

**Comment by GerbertKaandorp** [comment]
ps. I was thinking to (pre) generate the deletes in a multi-threaded queue or something.
I have 16 cores so hopefully I can go down from 26 minutes to 2 minutes :)

G

**Comment by erhanbaris** [comment]
Hi Gerber,
Let's talk at Gtalk or FB. Could you search my email address and add to your friend list?
